version: 2.1
orbs:
  node: circleci/node@1.0.1
executors:
  node_10:
    docker:
      - image: circleci/node:10.15

jobs:
  test:
    executor: node_10
    steps:
      - checkout # check out the code in the project directory
      - attach_workspace:
          at: ~/project
      - node/with-cache:
          cache-version: v1
          steps:
            - run:
                name: Yarn install
                command: yarn
            - run:
                name: Run all tests
                command: yarn test
      - persist_to_workspace:
          root: .
          paths: coverage

  sonarqube:
    executor: node_10
    steps:
      - checkout # check out the code in the project directory
      - attach_workspace:
          at: ~/project
      - node/with-cache:
          steps:
            - run:
                name: Generate eslint report
                command: yarn lint:sonarqube
            - restore_cache:
                keys:
                  - sonar-scanner-{{ .Branch }}
                  - sonar-scanner
            - run:
                name: Run sonar scanner
                command: yarn sonar-scanner -Dsonar.login=$SONAR_LOGIN || true
            - save_cache:
                key: sonar-scanner-{{ .Branch }}
                paths:
                  - /home/circleci/.sonar
  build:
    executor: node_10
    steps:
      - checkout # check out the code in the project directory
      - attach_workspace:
          at: ~/project
      - node/with-cache:
          steps:
            - run:
                name: Build build dir
                command: yarn build
      - persist_to_workspace:
          root: .
          paths: build

  release:
    executor: node_10
    steps:
      - checkout # check out the code in the project directory
      - attach_workspace:
          at: ~/project
      - node/with-cache:
          steps:
            - run:
                name: release
                command: yarn semantic-release || true

workflows:
  version: 2
  test_build_release:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/

      - sonarqube:
          context: zds
          requires:
            - test
          filters:
            branches:
              only:
                - development
                - master
            tags:
              only: /^v.*/

      - build:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/

      - release:
          context: zds
          requires:
            - build
          filters:
            branches:
              only:
                - master
            tags:
              only: /^v.*/